[en.translation]
unlockMessage = "Unlock open2FA"
loadFile = "Load File"
createFile = "Create File"
goBack = "Go Back"
iterations = "Iterations"
password = "Password"
createFileInstruction = "Here you can create a file in which you store services hashes with which app generates 6 digit codes for 2FA. It will be encrypted with your password, so make sure it is secure. Iterations is a number that dictates how long it takes to crack your password. But be aware that the larger the number, the longer it will take to decrypt it."
createFileWarning = "After clicking create file you have to wait a few seconds. After that a share prompt will appear in which you can save the file onto your disc or cloud"
loadFileTitle = "Type password to decrypt file"
wrapperMessage1 = "File functions in progress"
wrapperMessage2 = "It may take a few seconds"
noPlatformsMessage = "No platforms registered"
home = "Home"
qrScan = "Qr Scan"
settings = "Settings"
qrScanTitle = "Scan the QR code on the website where you are enabling 2FA"
scanQrCode = "Scan QR Code"
cancelScaning = "Cancel Scaning"

[pl.translation]
unlockMessage = "Odblokuj open2FA"
loadFile = "Załaduj Plik"
createFile = "Stwórz Plik"
goBack = "Powrót"
password = "Hasło"
iterations = "Iteracje"
createFileInstruction = "Tutaj możesz utworzyć plik, w którym przechowujesz skróty usług, za pomocą których aplikacja generuje 6-cyfrowe kody dla 2FA. Będzie on zaszyfrowany Twoim hasłem, więc upewnij się, że jest bezpieczny. Iteracje to liczba określająca czas potrzebny do złamania hasła. Należy jednak pamiętać, że im większa liczba, tym dłużej zajmie odszyfrowanie hasła."
createFileWarning = "Po kliknięciu przycisku Utwórz plik należy odczekać kilka sekund. Następnie pojawi się okno udostępniania, w którym można zapisać plik na dysku lub w chmurze."
loadFileTitle = "Podaj hasło do odszyfrowania pliku"
wrapperMessage1 = "Funkcje plików działają w tle"
wrapperMessage2 = "To może chwilę zająć"
noPlatformsMessage = "Brak zapisanych usług"
home = "Strona Główna"
qrScan = "Skan Qr"
settings = "Ustawienia"
qrScanTitle = "Zeskanuj kod QR na stronie internetowej, na której włączasz 2FA."
scanQrCode = "Skanuj kod QR"
cancelScaning = "Anuluj Skanowanie"
